export enum MOUSE_BUTTON {
  LEFT = 0,
  MIDDLE = 1,
  RIGHT = 2
}

export enum PHOTOMETRIC_INTERPRETATION {
  MONOCHROME1 = 'MONOCHROME1',
  MONOCHROME2 = 'MONOCHROME2'
}

export enum PIXEL_REPRESENTATION {
  SIGNED = 1,
  UNSIGNED = 0
}
